sudo: true
language: python
python:
#  - 2.7
  - 3.6
  - "nightly"
cache: pip
before_install:
  - sudo apt-get install libgnutls28-dev
  - make deps-dev
install:
  - make
script:
  - make coverage-publish codecov-publish doc
  - make publish-test
after_success:
  - make publish
## Create release in GitHub
deploy:
  provider: pages
  local_dir: docs/_build/html
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  on:
    branch: master
